apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ombi
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: ombi.local
    http:
      paths:
      - path: /
        backend:
          serviceName: ombi
          servicePort: 5000
  